<?php

declare(strict_types=1);

namespace ExamplePress\MU\Agent;

/**
 * Value object representing a single LLM generation result.
 *
 * Produced by LLMClient, consumed by GenerationJob. The shape mirrors
 * the JSON schema enforced on the LLM via Prism.
 *
 * Two output modes:
 *
 * 1. Generate mode — $filesChanged is the FULL file tree of a new app
 *    and $filesDeleted is always empty.
 *
 * 2. Iterate/Repair mode — $filesChanged contains only the files the
 *    LLM actually touched, and $filesDeleted lists explicit removals.
 *    The job merges these against the parent tree to produce the final
 *    tree. This is how we avoid the "LLM runs out of output tokens
 *    trying to regurgitate 40 unchanged files" trap.
 */
final class GeneratedApp
{
    /**
     * @param array<string,mixed>                            $manifest      Decoded examplepress.json the LLM produced.
     * @param array<int,array{path:string,contents:string}>  $filesChanged  Files the LLM is asserting or replacing.
     * @param array<int,string>                              $filesDeleted  Paths the LLM is explicitly removing.
     * @param string                                         $commitMessage Conventional commit message.
     * @param string                                         $version       Semver string (e.g. "1.0.0").
     */
    public function __construct(
        public readonly array $manifest,
        public readonly array $filesChanged,
        public readonly array $filesDeleted,
        public readonly string $commitMessage,
        public readonly string $version,
    ) {}

    /**
     * Build from a raw decoded JSON payload returned by Prism.
     *
     * @param array<string,mixed> $payload
     */
    public static function fromArray(array $payload): self
    {
        $changed = [];
        if (is_array($payload['files_changed'] ?? null)) {
            foreach ($payload['files_changed'] as $f) {
                if (!is_array($f) || !isset($f['path'])) {
                    continue;
                }
                $changed[] = [
                    'path'     => (string) $f['path'],
                    'contents' => (string) ($f['contents'] ?? ''),
                ];
            }
        }

        $deleted = [];
        if (is_array($payload['files_deleted'] ?? null)) {
            foreach ($payload['files_deleted'] as $p) {
                if (is_string($p) && $p !== '') {
                    $deleted[] = $p;
                }
            }
        }

        return new self(
            manifest: is_array($payload['manifest'] ?? null) ? $payload['manifest'] : [],
            filesChanged: $changed,
            filesDeleted: $deleted,
            commitMessage: (string) ($payload['commit_message'] ?? 'Generated by ExamplePress Agent'),
            version: (string) ($payload['version'] ?? '1.0.0'),
        );
    }

    /**
     * Merge this generation against a parent file tree. For
     * generate-mode results the parent should be empty, so the result
     * is exactly $filesChanged. For iterate/repair the parent tree is
     * the previous published or stashed version.
     *
     * Rules:
     *   - Any path in $filesChanged wins over the same path in parent.
     *   - Any path in $filesDeleted is removed from the output.
     *   - Any path not mentioned in either keeps its parent contents.
     *
     * @param array<int,array{path:string,contents:string}> $parentFiles
     * @return array<int,array{path:string,contents:string}>
     */
    public function mergeOnto(array $parentFiles): array
    {
        $merged = [];
        foreach ($parentFiles as $file) {
            if (!is_array($file) || !isset($file['path'])) {
                continue;
            }
            $merged[(string) $file['path']] = [
                'path'     => (string) $file['path'],
                'contents' => (string) ($file['contents'] ?? ''),
            ];
        }
        foreach ($this->filesChanged as $file) {
            $merged[$file['path']] = $file;
        }
        foreach ($this->filesDeleted as $path) {
            unset($merged[$path]);
        }
        return array_values($merged);
    }
}
