<?php

declare(strict_types=1);

namespace ExamplePress\MU\Agent;

/**
 * Value object representing a single LLM generation result.
 *
 * Produced by LLMClient, consumed by GenerationJob. The shape mirrors
 * the JSON schema enforced on the LLM via Prism.
 */
final class GeneratedApp
{
    /**
     * @param array<string,mixed>                              $manifest       Decoded examplepress.json the LLM produced.
     * @param array<int,array{path:string,contents:string}>  $files          File list (path relative to plugin root).
     * @param string                                           $commitMessage  Conventional commit message.
     * @param string                                           $version        Semver string (e.g. "1.0.0").
     */
    public function __construct(
        public readonly array $manifest,
        public readonly array $files,
        public readonly string $commitMessage,
        public readonly string $version,
    ) {}

    /**
     * Build from a raw decoded JSON payload returned by Prism.
     *
     * @param array<string,mixed> $payload
     */
    public static function fromArray(array $payload): self
    {
        return new self(
            manifest: is_array($payload['manifest'] ?? null) ? $payload['manifest'] : [],
            files: is_array($payload['files'] ?? null) ? array_values($payload['files']) : [],
            commitMessage: (string) ($payload['commit_message'] ?? 'Generated by ExamplePress Agent'),
            version: (string) ($payload['version'] ?? '1.0.0'),
        );
    }

    /**
     * @return array<string,mixed>
     */
    public function toArray(): array
    {
        return [
            'manifest'       => $this->manifest,
            'files'          => $this->files,
            'commit_message' => $this->commitMessage,
            'version'        => $this->version,
        ];
    }
}
